### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by drawcard** [nsaovh/nocdn#1]
Hi,

I'd like to use this project, but my government clients (who benefit the most from something like this) would never let me implement this in their code, because of the fairly obvious curse word in the project title.

Would you perhaps consider renaming to something like "NoCDN" instead?

**Comment by skid9000** [comment]
Hi @drawcard,

I'll talk to the other members, but you're right ^^

FuckCDN is our first concrete project so finding a name is quite complicated sometimes.

- Skid

**Comment by luclu7** [comment]
I think NoCDN is a good name for that, through you can install it on any (sub)domain.

**Comment by skid9000** [comment]
Solved, the project has been renamed as "NoCDN".

 - Skid

**Comment by drawcard** [comment]
Thank you for your consideration!
